TARGET = run

all: $(TARGET)

$(TARGET): lexer.cmo parser.cmo eval.cmo main.cmo
	ocamlc -o $@ $^

eval.cmo : eval.ml
	ocamlc -c eval.ml

parser.ml: parser.mly eval.cmo
	ocamlyacc parser.mly

parser.mli: parser.mly
	ocamlyacc parser.mly

parser.cmi: parser.mli
	ocamlc -c parser.mli

parser.cmo: parser.ml parser.cmi
	ocamlc -c parser.ml

main.cmo : eval.cmo main.ml
	ocamlc -c main.ml

lexer.cmo: lexer.ml
	ocamlc -c lexer.ml

lexer.ml: lexer.mll parser.cmo
	ocamllex lexer.mll

clean:
	rm -f *.cmx *.cmi parser.mli parser.ml lexer.ml run *.o *.cmo